# Generated by Django 3.1.3 on 2021-09-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0002_student_remaining_lesson_j'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
