# Generated by Django 3.2.7 on 2021-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0004_auto_20211002_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='照片'),
        ),
    ]
