# Generated by Django 3.2.7 on 2021-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0005_alter_teacher_imgae'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='照片'),
        ),
    ]
