# Generated by Django 3.2.7 on 2021-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0006_curriculum_imgae'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Number_of_classes',
            field=models.IntegerField(default=0),
        ),
    ]
