# Generated by Django 3.2.7 on 2021-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0007_teacher_number_of_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='month',
            field=models.IntegerField(default=10),
        ),
    ]
