# Generated by Django 3.2.7 on 2021-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainqeb', '0008_teacher_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='curriculum',
            field=models.ManyToManyField(blank=True, default=' ', null=True, to='mainqeb.Curriculum', verbose_name='课程'),
        ),
    ]
