# Generated by Django 3.2.7 on 2021-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='date',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=10),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021)], default=2021),
        ),
    ]
