# Generated by Django 3.2.7 on 2021-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20211002_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='follow',
            field=models.CharField(choices=[('王雨晴', '王雨晴'), ('胡雅丽', '胡雅丽'), ('谢立虎', '谢立虎'), ('刘玲', '刘玲'), ('陈米如', '米如'), ('李兰', '李兰')], max_length=50),
        ),
    ]
